m3o/backend

Dockerfile
entrypoint.sh

Should prevent any zombies from being left behind

Add dumb init to micro/services image

---

.github/workflows/build.yml
event.sh

Build a single GitHub package per service when it changes.

Build one package per service

---

platform/scheduler/manager/manager.go
platform/scheduler/manager/manager_test.go

Fixes the `Unrecognized service status: 'updated'` error.

Minor platform scheduler fixes

---

docs/web/content/pages/users.md

Added BetMakers

---

docs/web/content/pages/getting-started.md

First cut, unfinished, probably full of typos.

[WIP] Getting started guide

---

docs/web/content/css/customstyles.css
docs/web/content/css/lavish-bootstrap.css
docs/web/html/css/customstyles.css
docs/web/html/css/lavish-bootstrap.css
docs/web/html/feed.xml
docs/web/html/search.json
docs/web/html/sitemap.xml

Trying to get rid of the malformed `micro status` here: https://micro.mu/docs/getting-started.html

Nuke white space wrap in blog

---

helloworld/go.mod
helloworld/go.sum

update dep for helloworld

---

cockroachdb/backup/README.md
cockroachdb/backup/lifecycle.xml

add lifecycle policy for s3 bucket

---

.github/workflows/docker.yml
go.mod
go.sum

so we don't just push to latest

snapshot docker images

---

status/handler/status.go

Was returning a 200 HTTP code even on error

make status call return error correctly

---

signup/handler/signup.go

Configurable payment message for signup service

---

signup/handler/signup.go

Currently a user must complete signup within 5 mins before their OTP expires. This 5 mins expiry includes paying via Stripe and there are many reasons why this part might take longer; user gets distracted, needs to find their credit card, whatever. 
Up for debate but I think we should only check for expiry in the first verify step. When they complete signup we can still check that the token is correct but not check for whether they've done it within the expiry duration.
Also - not expiring out these records means that we have a record of email addresses attempting signup

only verify expiry of OTP on the verify step and not the complete step

---

tests/integration/signup/signup_test.go

See 'Test proofrun' commit which should fail for proof that the tests are working.

Test stripe subscriptions

---

alert/handler/alert.go

We don't need Slack alerts in staging.
We could check for an empty slack token too but I wanted to make turning off slack explicit, and being on by default.

Ability to turn off Slack messages

---

.github/workflows/integration-m3o.yml
tests/image/Dockerfile
tests/image/run-etcd.sh
tests/image/test-docker.sh

Faster m3o integration tests

---

.github/workflows/integration-m3o.yml
signup/handler/signup.go
tests/integration/signup/signup_test.go

+ testing for payment message in signup output.

signup: Default payment message if not provided

---

customers/handler/customer.go
go.sum
invite/handler/handler.go
signup/handler/signup.go

and make invite only signup config driven

Check customer exists before trying to create

---

go.mod
go.sum

bump micro

---

balance/handler/events.go
onboarding/handler/events.go
usage/handler/events.go

To compensate for weird behaviour with dropped connections not being noticed.

Reconnect to stream if no activity for 2 minutes

---

endtoend/handler/endtoend.go
go.mod
go.sum
v1/handler/v1.go

Make e2e test less sensitive so that it only flags a fail if more than one API fails examples

Better monitoring

---

balance/handler/balance.go
balance/handler/events.go
endtoend/handler/endtoend.go
onboarding/handler/events.go
v1/handler/keys.go
v1/handler/v1.go

Need to check balance as part of v1api calls. Adds latency to the critical path but hopefully an acceptable amount. 
We'll continue decrementing of the balance as an async process.

Move balance check to the critical path

---

alert/handler/alert.go
v1/handler/v1.go

Use a background context rather than the request one which will get cancelled when request is done

Fix up context
